version: '3.8'

volumes:
  postgres_data:
  nginx:
  static:

services:
  db:
    image: postgres:12.4
    container_name: drf_yamdb_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: volhadounar87/yamdb_final:v1.2021
    restart: always
    container_name: drf_yamdb_web
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./static:/static
    container_name: drf_yamdb_nginx
    ports:
      - "80:80"
    depends_on:
      - web
