# Generated by Django 3.0.5 on 2020-11-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailConfirmation',
        ),
    ]
