# Generated by Django 3.0.5 on 2020-11-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201120_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('-id',)},
        ),
    ]
